title: "Jamison Johnson's Portfolio"
author: "Jamison Johnson"
description: "Technology Is Inspiration"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

shoe_social: true
show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
#minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md"} 
#  - {file: "README.md"} 
  - {file: "resume.md"} 
  - {title: "Reviews", url: "https://jpcreviews.github.io"}
  - {title: "Blog", url: "https://johnsonpremier.github.io"}


external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:johnsonpremierconsulting@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/jamisonjohnson/jamisonjohnson.github.io"}
  - {title: Instagram, icon: instagram, url: "https://www.instagram.com/johnsonpremierconsulting/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
